# Generated by Django 5.1.1 on 2024-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_photo_car_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarInvetory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_count", models.IntegerField()),
                ("car_value", models.FloatField()),
                ("created_at", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
